import Item from "./item"
import "../App.css"


function Listado () {
    return (
      <div className="imagen-L">
      <div className="App">
        
        <div className='contenedor-principal'>
          
        <h2>Caballeros Dorados De Las 12 Casas</h2>
  
       <Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m "
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="Aries"
      imagen2="cajaaries"
      imagen3="Mu"
      />

<Item
       nombre="Tauro"
      sexo="masculino"
      fechaDeNacimiento="8 de mayo"
      edad="20"
      origen="Manga"
      primeraAparicion="Casa dorada de Tauro"
      funsion="Caballero de Tauro"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="2,10 m "
      peso="130 kg (286 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Brazil"
      familia="Shion de Aries (maestro)"
      kiki="none"
      lugarDeEntrenamiento="Brazil"
      habilidades="Santo de oro"
      constelacion="Tauro"
      tecnicas="	
      Great Horn
      Iron Arm (Episodio G)"
      imagen="aldebaran"
      imagen2="cajaaries"
      imagen3="Tauro"
      />

<Item
       nombre="Saga"
      sexo="masculino"
      fechaDeNacimiento="30 de mayo"
      edad="28"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,88 m "
      peso="87 kg (191 lb) kg"
      ocupacion="(Antagonista) Santo de Atenea"
      procedencia = "Grecia"
      familia="Kanon (hermano Gemelo"
      kiki="None"
      lugarDeEntrenamiento="Santuario Grecia"
      habilidades="Santo de oro"
      constelacion="Geminis"
      tecnicas="	
      * Galaxian Explosion
      * Otra Dimension"
      imagen="saga"
      imagen2="cajaaries"
      imagen3="saga maligno"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="cancer"
      imagen2="cajaaries"
      imagen3="Cancer1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="leo"
      imagen2="cajaaries"
      imagen3="Leo1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="virgo"
      imagen2="cajaaries"
      imagen3="Virgo1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="libra"
      imagen2="cajaaries"
      imagen3="Libra1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="escorpion"
      imagen2="cajaaries"
      imagen3="Scorpion"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="sagitario"
      imagen2="cajaaries"
      imagen3="Sagitario1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="capricornio"
      imagen2="cajaaries"
      imagen3="Capricornio1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="acuario"
      imagen2="cajaaries"
      imagen3="Acuario1"
      />

<Item
       nombre="Aries"
      sexo="masculino"
      fechaDeNacimiento="27 de marzo"
      edad="20"
      origen="Manga"
      primeraAparicion="Torneo Galáctico"
      funsion="Caballero de Aries"
      manga="Capítulo 3"
      anime="Episodio 10"
      estatura="1,82 m (60″) m"
      peso="75 kg (165 lb) kg"
      ocupacion="Santo de Atenea"
      procedencia = "Flag of Tibet Tíbet"
      familia="Shion de Aries (maestro)"
      kiki="(discípulo)"
      lugarDeEntrenamiento="Jamir"
      habilidades="speciales Santo de oro"
      constelacion="Aries"
      tecnicas="	
      Crystal Net
      Crystal Wall"
      imagen="picis"
      imagen2="cajaaries"
      imagen3="Picis1"
      />

       
       </div>
        </div>
      </div>
    );
  }
  
  export default Listado;